[package]
name = "engine_assets"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
tobj.workspace = true
serde.workspace = true
serde_json.workspace = true
image.workspace = true
bytemuck.workspace = true

