[package]
name = "engine_ecs"
version = "0.1.0"
edition = "2024"

[dependencies]
engine_assets = { path = "../assets" }
bevy_ecs.workspace = true
glam.workspace = true
winit.workspace = true
serde.workspace = true
serde_json.workspace = true
bytemuck.workspace = true

